DROP TABLE IF EXISTS API_KEY;
DROP TABLE IF EXISTS PROPERTY;
DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS CATEGORY;

CREATE TABLE PROPERTY (
    PROPERTY_ID     VARCHAR (50) NOT NULL,
    NAME            VARCHAR (250) NOT NULL,
    DESCRIPTION     VARCHAR (500),
    PRICE           DOUBLE,
    PROPERTY_TYPE   VARCHAR (50),
    STATUS          VARCHAR (20),
    STATUS_COMMENT  VARCHAR (250),
    STATUS_DATE     TIMESTAMP (6),
    UPDATED_USR_ID  VARCHAR (50),
    UPDATED_TIMSTM  TIMESTAMP (6),
    PRIMARY KEY ("PROPERTY_ID")
);

CREATE TABLE API_KEY (
    ID              NUMBER NOT NULL,
    KEY             VARCHAR (50) NOT NULL,
    PRIMARY KEY ("ID")
);

CREATE TABLE `CONTACT` (
     `ID_CONTACT` VARCHAR (50) NOT NULL,
     `USER_NAME` VARCHAR(255) NOT NULL,
     `EMAIL` VARCHAR(45) NOT NULL,
     `MESSAGE` MEDIUMTEXT NOT NULL,
     PRIMARY KEY (`ID_CONTACT`));

CREATE TABLE POST (
      `ID_POST` VARCHAR(50) NOT NULL,
      `IMG_NAME` VARCHAR(255) NOT NULL,
      `IMG_URL` VARCHAR(255) NOT NULL,
      `TITLE` VARCHAR(255) NOT NULL,
      `CREATE_DATE` TIMESTAMP NULL,
      `CREATE_BY` VARCHAR(255) NULL,
      `MODIFY_DATE` TIMESTAMP NULL,
      `MODIFY_BY` VARCHAR(255) NULL,
      `DESCRIPTION`  VARCHAR(255) NOT NULL,
      `CONTENT` LONGTEXT NOT NULL,
      `CATEGORY_ID` VARCHAR(255) NOT NULL,
      PRIMARY KEY (`ID_POST`));


CREATE TABLE CATEGORY (
     ID_CATEGORY   VARCHAR(50) NOT NULL,
     NAME  VARCHAR (255) NOT NULL,
     PRIMARY KEY ("ID_CATEGORY")
);
